language: perl
perl:
    - "5.8.9" # 3-part version to ensure core-only Perl
    - "5.10.1" # 3-part version to ensure core-only Perl
    - "5.26"
    - "5.26.0"
    - "blead"

matrix:
    include:
        - perl: '5.26'
          env: COVERAGE=1
        - perl: "5.26"
          env: DEVEL_HIDE_PM="YAML::XS"
    allow_failures:
        - perl: "blead"

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - cpan-install Devel::Hide
    - build-dist
    - cd $BUILD_DIR

install:
    - cpan-install --deps
    - cpan-install --coverage

before_script:
    - coverage-setup

script:
    - perl Makefile.PL
    - make
    - export PERL5OPT="-MDevel::Hide"
    - export DEVEL_HIDE_VERBOSE=0
    - prove -bl -s -j$(test-jobs) $(test-files)

after_success:
    - coverage-report
